export const PATHS = {
  DASHBOARD: 'dashboard',
  DASHBOARD_NFTS: 'dashboard/nfts',
  AUTH: 'auth',
  PROFILE: 'profile',
  SIGN_UP: 'auth/sign-up',
  SIGN_IN: 'auth/sign-in',
  SIGN_IN_TEMPLATE_DRIVEN: 'auth/sign-in-template-driven',
  FORGOT_PASSWORD: 'auth/forgot-password',
  NEW_PASSWORD: 'auth/new-password',
  TWO_STEPS: 'auth/two-steps',
  ERRORS: 'errors',
  ERROR_404: 'errors/404',
  ERROR_500: 'errors/500',
  FEATURES_UI: 'features/ui',
  FEATURES_TABLE: 'features/ui/table',
  DOWNLOAD: 'download',
  GIFT: 'gift',
  USERS: 'users',
  SETTINGS: 'settings',
  NOTIFICATIONS: 'gift',
  FOLDERS: 'folders',
  FOLDERS_CURRENT_FILES: 'folders/current-files',
  FOLDERS_DOWNLOAD: 'folders/download',
  FOLDERS_TRASH: 'folders/trash',
};
